/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package selector.GUI;

import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;

/**
 *
 * @author Shaw
 */
public class Inicio extends javax.swing.JFrame {
    String pj;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        inicializarVariables();
        
    }
    
    private void inicializarVariables(){
        pj = "chico";
        jButtonLlamar.setText("Llamar " + pj);
    }
    
    public void setNewCharacter(ImageIcon img, String [] stats){
        jLabelPJ.setIcon(img);
        jLabelValorNombre.setText(stats[0]);
        jLabelValorVictorias.setText(stats[1]);
        jLabelValorDerrotas.setText(stats[2]);
        jLabelValorBatallas.setText(stats[3]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelStats = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelValorNombre = new javax.swing.JLabel();
        jLabelVictorias = new javax.swing.JLabel();
        jLabelValorVictorias = new javax.swing.JLabel();
        jLabelDerrotas = new javax.swing.JLabel();
        jLabelValorDerrotas = new javax.swing.JLabel();
        jLabelBatallas = new javax.swing.JLabel();
        jLabelValorBatallas = new javax.swing.JLabel();
        jButtonLlamar = new javax.swing.JButton();
        jPanelSpritePJ = new javax.swing.JPanel();
        jLabelPJ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelStats.setLayout(new java.awt.GridLayout(8, 0));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNombre.setText("Nombre");
        jPanelStats.add(jLabelNombre);

        jLabelValorNombre.setText("_");
        jPanelStats.add(jLabelValorNombre);

        jLabelVictorias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelVictorias.setText("Victorias");
        jPanelStats.add(jLabelVictorias);

        jLabelValorVictorias.setText("_");
        jPanelStats.add(jLabelValorVictorias);

        jLabelDerrotas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDerrotas.setText("Derrotas");
        jPanelStats.add(jLabelDerrotas);

        jLabelValorDerrotas.setText("_");
        jPanelStats.add(jLabelValorDerrotas);

        jLabelBatallas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBatallas.setText("Batallas");
        jPanelStats.add(jLabelBatallas);

        jLabelValorBatallas.setText("_");
        jPanelStats.add(jLabelValorBatallas);

        jButtonLlamar.setText("Llamar ...");
        jButtonLlamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLlamarActionPerformed(evt);
            }
        });

        jPanelSpritePJ.setBackground(new java.awt.Color(255, 200, 106));

        jLabelPJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selector/GUI/Recursos/chicoPq.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSpritePJLayout = new javax.swing.GroupLayout(jPanelSpritePJ);
        jPanelSpritePJ.setLayout(jPanelSpritePJLayout);
        jPanelSpritePJLayout.setHorizontalGroup(
            jPanelSpritePJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSpritePJLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSpritePJLayout.setVerticalGroup(
            jPanelSpritePJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSpritePJLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLlamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSpritePJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelStats, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStats, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jPanelSpritePJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLlamar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLlamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLlamarActionPerformed
        // TODO add your handling code here:
        Selector sl = new Selector(this, true);
        sl.setVisible(true);
    }//GEN-LAST:event_jButtonLlamarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLlamar;
    private javax.swing.JLabel jLabelBatallas;
    private javax.swing.JLabel jLabelDerrotas;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPJ;
    private javax.swing.JLabel jLabelValorBatallas;
    private javax.swing.JLabel jLabelValorDerrotas;
    private javax.swing.JLabel jLabelValorNombre;
    private javax.swing.JLabel jLabelValorVictorias;
    private javax.swing.JLabel jLabelVictorias;
    private javax.swing.JPanel jPanelSpritePJ;
    private javax.swing.JPanel jPanelStats;
    // End of variables declaration//GEN-END:variables
}
