/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package selector.GUI;

import java.awt.Image;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Shaw
 */
public class Selector extends javax.swing.JDialog {

    final DefaultListCellRenderer dlcr = new DefaultListCellRenderer();
    final ImageIcon chico = new ImageIcon(getClass().getResource("recursos/chico.png"));
    final ImageIcon chicoPq = new ImageIcon(getClass().getResource("recursos/chicoPq.png"));
    final ImageIcon chica = new ImageIcon(getClass().getResource("recursos/chica.png"));
    final ImageIcon chicaPq = new ImageIcon(getClass().getResource("recursos/chicaPq.png"));
    final String defaultMSGNombre = "Escribe tu nombre";
    boolean dadoTirados = false;
    String[] stats;
    Inicio inicio;

    /**
     * Creates new form Selector
     */
    public Selector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicio = (Inicio) parent;
        dlcr.setHorizontalAlignment(DefaultListCellRenderer.CENTER);
        jTextFieldNombre.setText(defaultMSGNombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInfoPJ = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelVictorias = new javax.swing.JLabel();
        jLabelValorVictorias = new javax.swing.JLabel();
        jLabelDerrotas = new javax.swing.JLabel();
        jLabelValorDerrotas = new javax.swing.JLabel();
        jLabelBatallas = new javax.swing.JLabel();
        jLabelValorBatallas = new javax.swing.JLabel();
        jComboBoxPJs = new javax.swing.JComboBox<>();
        jPanelIMG = new javax.swing.JPanel();
        jLabelFotoPersonaje = new javax.swing.JLabel();
        jButtonDados = new javax.swing.JButton();
        jButtonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelInfoPJ.setLayout(new java.awt.GridLayout(4, 2, 5, 0));

        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNombre.setText("Nombre:");
        jPanelInfoPJ.add(jLabelNombre);

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanelInfoPJ.add(jTextFieldNombre);

        jLabelVictorias.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVictorias.setText("Victorias:");
        jPanelInfoPJ.add(jLabelVictorias);

        jLabelValorVictorias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelValorVictorias.setText("0");
        jPanelInfoPJ.add(jLabelValorVictorias);

        jLabelDerrotas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDerrotas.setText("Derrotas:");
        jPanelInfoPJ.add(jLabelDerrotas);

        jLabelValorDerrotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelValorDerrotas.setText("0");
        jPanelInfoPJ.add(jLabelValorDerrotas);

        jLabelBatallas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBatallas.setText("Batallas:");
        jPanelInfoPJ.add(jLabelBatallas);

        jLabelValorBatallas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelValorBatallas.setText("0");
        jPanelInfoPJ.add(jLabelValorBatallas);

        jComboBoxPJs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxPJs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chico", "Chica" }));
        jComboBoxPJs.setRenderer(dlcr);
        jComboBoxPJs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPJsActionPerformed(evt);
            }
        });

        jPanelIMG.setBackground(new java.awt.Color(255, 200, 106));
        jPanelIMG.setLayout(new java.awt.GridLayout(1, 1));

        jLabelFotoPersonaje.setBackground(new java.awt.Color(255, 200, 106));
        jLabelFotoPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFotoPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selector/GUI/Recursos/chico.png"))); // NOI18N
        jPanelIMG.add(jLabelFotoPersonaje);

        jButtonDados.setText("TIRAR DADOS");
        jButtonDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadosActionPerformed(evt);
            }
        });

        jButtonEnviar.setText("ENVIAR");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButtonEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(jButtonDados)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxPJs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelIMG, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInfoPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jComboBoxPJs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanelInfoPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDados)
                    .addComponent(jButtonEnviar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        if (dadoTirados && !(jTextFieldNombre.getText()).equals(defaultMSGNombre)) {
            stats = new String[]{jTextFieldNombre.getText(),
                jLabelValorVictorias.getText(),
                jLabelValorDerrotas.getText(),
                jLabelValorBatallas.getText()};
            String seleccionado = jComboBoxPJs.getItemAt(jComboBoxPJs.getSelectedIndex());
            inicio.setNewCharacter(seleccionado.equals("Chico") ? chicoPq : chicaPq, stats);
            setVisible(false);
        }else if ((jTextFieldNombre.getText()).equals(defaultMSGNombre)) {
             JOptionPane.showMessageDialog(rootPane, "No has establecido un nombre!!","ERROR",2);
        } else if (!dadoTirados){
            JOptionPane.showMessageDialog(rootPane, "No has tirado los dados!!","ERROR",2);
        }
        
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jComboBoxPJsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPJsActionPerformed
        // TODO add your handling code here:
        String seleccionado = jComboBoxPJs.getItemAt(jComboBoxPJs.getSelectedIndex());
        jLabelFotoPersonaje.setIcon(seleccionado.equals("Chico") ? chico : chica);
    }//GEN-LAST:event_jComboBoxPJsActionPerformed

    private void jButtonDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadosActionPerformed
        // TODO add your handling code here:
        jLabelValorVictorias.setText(random(100, 1) + "");
        jLabelValorDerrotas.setText(random(100, 1) + "");
        jLabelValorBatallas.setText(random(100, 1) + "");
        dadoTirados = true;
    }//GEN-LAST:event_jButtonDadosActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        // TODO add your handling code here:
        if ((jTextFieldNombre.getText()).equals(defaultMSGNombre)) {
            jTextFieldNombre.setText("");
        }
        
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        // TODO add your handling code here:
        if ((jTextFieldNombre.getText()).equals("")) {
            jTextFieldNombre.setText(defaultMSGNombre);
        }
    }//GEN-LAST:event_jTextFieldNombreFocusLost
    private int random(int max, int min) {
        return (int) (Math.random() * ((max + min) - min));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Selector dialog = new Selector(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDados;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JComboBox<String> jComboBoxPJs;
    private javax.swing.JLabel jLabelBatallas;
    private javax.swing.JLabel jLabelDerrotas;
    private javax.swing.JLabel jLabelFotoPersonaje;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelValorBatallas;
    private javax.swing.JLabel jLabelValorDerrotas;
    private javax.swing.JLabel jLabelValorVictorias;
    private javax.swing.JLabel jLabelVictorias;
    private javax.swing.JPanel jPanelIMG;
    private javax.swing.JPanel jPanelInfoPJ;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
